# This is a basic workflow to help you get started with Actions

name: new patch release

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0

      - name: Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
    
      - uses: bahmutov/npm-install@v1

      - name: Patch Version and Deploy
        run: npm run version:patch:build
      
      - name: Publish
        run: npm run lib:publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit files
        run: |
          newVersion=$(npm --silent run lib:version)
          git config --local user.email "release-bot@users.noreply.github.com"
          git config --local user.name "github-actions-release-bot"
          git add projects/angular-lingua/package.json
          git commit -m ":bookmark: Creating Patch release: v${newVersion}" 
          git tag "v${newVersion}"
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true