# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: cd angular-lingua-lib && npm ci
      - run: cd angular-lingua-lib && npm run build
      - run: cd angular-lingua-lib && npm run test:ci
