# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Node 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npm ci
      - name: Build Library
        run: npm run build:lib
      - name: Build Sample
        run: npm run build:sample
      - run: npm run test:ci
      - run: npm run e2e
